---
title: "Probability Theory"
---

::: callout-note
Assignment I on Probability Theory - final submission
:::


# Assignment 1 - Solution 


```{r}
# Given Probabilities
p_S = 0.3 # probability of having a change in scope
p_S_prime = 0.7 # probability of having no change in scope
p_T_given_S = 0.2 # probability of being on time given a change in scope
p_T_prime_given_S = 0.8 # probability of not being on time given a change in scope
p_T_given_S_prime = 0.6 # probability of being on time given no change in scope
p_T_prime_given_S_prime = 0.4 # probability of not being on time given no change in scope

#intersection probabilities
p_T_and_S = p_S * p_T_given_S
p_T_and_S_prime = p_S_prime * p_T_given_S_prime
p_T_prime_and_S = p_S * p_T_prime_given_S
p_T_prime_and_S_prime = p_S_prime * p_T_prime_given_S_prime
```

## Result
```{r}

#results
cat("P(T ∩ S) = ", p_T_and_S, "\n")
cat("P(T ∩ S') = ", p_T_and_S_prime, "\n")
cat("P(T' ∩ S) = ", p_T_prime_and_S, "\n")
cat("P(T' ∩ S') = ", p_T_prime_and_S_prime, "\n")

#sum of all four probabilities
sum_prob = p_T_and_S + p_T_and_S_prime + p_T_prime_and_S + p_T_prime_and_S_prime
cat("The sum of all four probabilities = ", sum_prob, "\n")

```

# Assignment 2 - Solution
```{r}
# What is the percentage of customers using all three devices?
percentage_all_three_devices <- 0.5

# What is the percentage of customers using at least two devices?
percentage_at_least_two_devices <- 7.3 + 3.3 + 8.8 + 0.5

# What is the percentage of customers using only one device?
percentage_only_one_device <- 42.3 + 27.8 + 10

```
## Result
```{r}
# Print the answers
print(paste("Percentage of customers using all three devices: ", percentage_all_three_devices, "%"))
print(paste("Percentage of customers using at least two devices: ", percentage_at_least_two_devices, "%"))
print(paste("Percentage of customers using only one device: ", percentage_only_one_device, "%"))

```

# Assignment 3 - Solution
```{r}
# Known probabilities
P_B_given_A <- 0.97
P_B_given_not_A <- 0.01
P_A <- 0.04

# Compute P(not A)
P_not_A <- 1 - P_A

# Compute P(B)
P_B <- P_B_given_A * P_A + P_B_given_not_A * P_not_A

# Compute P(A|B) and P(not A|B)
P_A_given_B <- (P_B_given_A * P_A) / P_B
P_not_A_given_B <- (P_B_given_not_A * P_not_A) / P_B 

# Print the results
print(paste("P(A|B) =", P_A_given_B))
print(paste("P(not A|B) =", P_not_A_given_B))

P_A_given_B <- P_A_given_B*100
P_not_A_given_B <- P_not_A_given_B *100
```
## Result
```{r}
# Print the answers

print(paste("These results show than in case the alarm is triggered, there is a posibility of about ",P_not_A_given_B," % that the product is flawless and a probability of ", P_A_given_B, " % that the product is faulty"))


```




