{
  "hash": "ea446525926cda9304a5871b9c4fbca5",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\nauthor: \"Sophia Wynona\"\n---\n\n\n::: callout-note\nAssignment V on Directed Acyclic Graphs - final submission\n:::\n\n# Task 1\n\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_99b6251c116857d8c8610e959a821e59'}\n\n```{.r .cell-code}\ninstall.packages(\"ggdag\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: package 'ggdag' is in use and will not be installed\n```\n:::\n\n```{.r .cell-code}\ninstall.packages(\"dplyr\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: package 'dplyr' is in use and will not be installed\n```\n:::\n\n```{.r .cell-code}\ninstall.packages(\"ggplot2\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: package 'ggplot2' is in use and will not be installed\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggdag)\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Your data\nstore_data <- data.frame(\n  Store = c(\"A\", \"B\", \"C\", \"D\"),\n  y0 = c(135, 121, NA, NA),\n  y1 = c(NA, NA, 102, 94),\n  d = c(0, 0, 1, 1),\n  y = c(135, 121, 102, 94),\n  ITE = c(NA, NA ,NA ,NA)\n)\n\n# Create a DAG\ndag <- dagify(y ~ d + y0 + y1,\n              d ~ y0,\n              y0 ~ ITE,\n              y1 ~ ITE,\n              exposure = \"d\",\n              outcome = \"y\",\n              latent = c(\"ITE\"),\n              coords = list(x = c(ITE = 1, y0 = 2, d = 3, y1 = 4, y = 5),\n                            y = c(ITE = 2, y0 = 1, d = 2, y1 = 1, y = 2)))\n\n# Plot the DAG\nggdag(dag) \n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n# Task 2\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_11e5cb1e8b76d1e818356bff799c9b30'}\n\n```{.r .cell-code}\n# Load the data\ndata <- readRDS(\"C:/Users/sophi/OneDrive/Desktop/Causal Data Science for Business Analytics 2023/gitclone/cdsba-swynona/assets/Causal_Data_Science_Data/customer_sat.rds\")\n\n# View the structure of the data\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> tibble [15 × 3] (S3: tbl_df/tbl/data.frame)\n#>  $ follow_ups  : num [1:15] 8 7 8 9 10 6 7 6 8 8 ...\n#>  $ satisfaction: num [1:15] 40 45 47 44 50 55 60 62 59 65 ...\n#>  $ subscription: chr [1:15] \"Elite\" \"Elite\" \"Elite\" \"Elite\" ...\n```\n:::\n\n```{.r .cell-code}\nmodel1 <- lm(satisfaction ~ follow_ups, data = data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n\n```{.r .cell-code}\nmodel2 <- lm(satisfaction ~ follow_ups + subscription, data = data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n# Task 3 \nComparing coefficients and explanations : \n\nIn Model 1, the coefficient for follow_ups is -3.3093. This suggests that for each additional follow-up call, the satisfaction decreases by 3.3093 units, assuming all other variables are held constant. This model does not account for the subscription variable.\nIn Model 2, the coefficient for follow_ups is 2.1944. This suggests that for each additional follow-up call, the satisfaction increases by 2.1944 units, when accounting for the subscription variable. This is a signifi cant change from Model 1, indicating that the subscription variable has a substantial impact on the relationship between follow_ups and satisfaction.\nThe coefficients for subscriptionPremium and subscriptionPremium+ are 44.7222 and 18.0722respectively. This suggests that the subscription level significantly affects customer satisfaction. Specifically, customers with a Premium subscription are, on average, 44.7222 units more satisfied than those with a Starter subscription, assuming all other variables are held constant. Similarly, customers with a Premium+ subscription are, on average, 18.0722 units more satisfied than those with a Starter subscription, assuming all other variables are held constant.\nIn conclusion, the subscription level appears to moderate the relationship between follow_upsand satisfaction. Without considering subscription, more follow-up calls are associated with lower satisfaction. However, when subscription is considered, more follow-up calls are associated with higher satisfaction. This could be because customers with higher-level subscriptions receive more benefits from follow-up calls, which increases their satisfaction. It’s also worth noting that customers with higher-level subscriptions are generally more satisfied.\n\n# Task 4 - Plotting\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_bcbcdeb2377700b72a76a059bd8b5af3'}\n\n```{.r .cell-code}\nggplot(data, aes(x = follow_ups, y = satisfaction)) +\n  geom_point() +\n  facet_wrap(~subscription) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(title = \"Relationship between Follow-ups and Satisfaction\",\n       x = \"Follow-ups\",\n       y = \"Satisfaction\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}