{
  "hash": "add553f7022a4d8ce03bc78aef916928",
  "result": {
    "markdown": "---\ntitle: \"Statistical Concepts\"\nauthor: \"Sophia Wynona\"\n---\n\n\n::: callout-note\nAssignment II on Statistical Concepts - final submission\n:::\n\n# Task 1\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-1_46d27f454efb59f836d2ecb173df45dd'}\n\n```{.r .cell-code}\nrandom_vars <- readRDS(\"C:/Users/sophi/OneDrive/Desktop/Causal Data Science for Business Analytics 2023/gitclone/cdsba-swynona/assets/Causal_Data_Science_Data/random_vars.rds\")\n\nexpected_value_age <- mean(random_vars$age, na.rm = TRUE)\nvariance_age <- var(random_vars$age, na.rm = TRUE)\nstandard_deviation_age <- sd(random_vars$age, na.rm = TRUE)\n\nprint(paste('Expected Value Age = ', expected_value_age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Expected Value Age =  33.471\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('Variance Age = ', variance_age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Variance Age =  340.607766766767\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('Standard Deviation Age = ', standard_deviation_age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Standard Deviation Age =  18.4555619466536\"\n```\n:::\n\n```{.r .cell-code}\nexpected_value_income <- mean(random_vars$income, na.rm = TRUE)\nvariance_income <- var(random_vars$income, na.rm = TRUE)\nstandard_deviation_income <- sd(random_vars$income, na.rm = TRUE)\n\nprint(paste('Expected Value Income = ', expected_value_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Expected Value Income =  3510.731\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('Variance Income = ', variance_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Variance Income =  8625645.84448348\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('Standard Deviation Income = ', standard_deviation_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Standard Deviation Income =  2936.94498492626\"\n```\n:::\n:::\n\n# Task 2\nIt makes sense to compare the standard deviations of age and income. The standard deviation is a measure of the amount of variation, a low standard deviation means that the values tend to be close to the mean (expected value), while a high standard deviation means that the values are more spread out over a wider range.\nIn this case, the standard deviation of age is approximately 18.46 years, and the standard deviation of income is approximately 2936.94 units. This means that the ages in the dataset are less spread out from the mean age than the incomes are from the mean income. This means there is more VARIABILITY in the INCOMES of the individuals in the dataset than in their AGES.\n\n# Task 3\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-2_b45e2597bd041c2b4e9c556bda85c7ef'}\n\n```{.r .cell-code}\ncovariance <- cov(random_vars$age, random_vars$income, use = \"na.or.complete\")\ncorrelation <- cor(random_vars$age, random_vars$income, use = \"na.or.complete\")\n\nprint(paste('Covariance = ',covariance))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Covariance =  29700.1468458458\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('Correlation = ',correlation))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Correlation =  0.547943162326477\"\n```\n:::\n:::\n\n# Task 4\nThe expected value (or mean) is often the easiest to interpret because it provides a measure of the “central tendency” or typical value of the data.\n\nIn this case, the expected value of age is approximately 33.47 years, which means that on average, the individuals in the dataset are around 33 years old. The expected value of income is approximately 3510.73 units, which means that on average, the individuals in the dataset earn around 3510 units of income.\n\nThe correlation, which is approximately 0.55, is also relatively straightforward to interpret. This value indicates a moderate positive relationship between age and income, meaning that as age increases, income tends to increase as well.\n\nVariance and standard deviation provide information about the spread or dispersion of the data, and covariance provides a measure of how much two variables change together. These measures can be a bit more difficult to interpret without additional context or information. \n\nFor example, the standard deviation of income is approximately 2936.94 units, but without knowing more about the distribution of income \nit’s hard to say exactly what this tells us. Similarly, the covariance is approximately 29700.15, but this value is difficult to interpret on its own because it depends on the units of measurement of the variables. The correlation coefficient, which is unitless and ranges from -1 to 1, is often easier to interpret.\n\n# Task 5\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-3_3ee5dff7b324437ed5172efb0003cc04'}\n\n```{.r .cell-code}\nE_income_age_less_18 <- mean(random_vars$income[random_vars$age <= 18], na.rm = TRUE)\nE_income_age_18_65 <- mean(random_vars$income[random_vars$age >= 18 & random_vars$age <= 65], na.rm = TRUE)\nE_income_age_greater_65 <- mean(random_vars$income[random_vars$age >= 65], na.rm = TRUE)\n\nprint(paste('5.1. Income less than Age 18 = ', E_income_age_less_18))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"5.1. Income less than Age 18 =  389.607438016529\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('5.2. Income between Age 18 and Age 65 = ', E_income_age_18_65))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"5.2. Income between Age 18 and Age 65 =  4691.3779637378\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste('5.3. Income more than Age 65 = ', E_income_age_greater_65))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"5.3. Income more than Age 65 =  1777.23728813559\"\n```\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}